# Generated by Django 3.1.7 on 2021-04-02 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('singer_name', models.CharField(max_length=100)),
                ('album_name', models.CharField(max_length=100)),
                ('upload_song', models.FileField(upload_to='./songs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
            ],
        ),
    ]
